---
- name: Create Windows AD Virtual Machine
  vmware_guest:
    hostname: "{{ vsphere_vcenter_hostname }}"
    username: "{{ vsphere_vcenter_username }}"
    password: "{{ vcenter_password }}"
    validate_certs: "{{ vsphere_vcenter_validate_certs }}"
    datacenter: "{{ vsphere_vcenter_datacenter }}"
    folder: "{{ vsphere_vm_folder }}"
    state: "{{ common_vm_state }}"
    name: "{{ inventory_guest_hostname }}"
    esxi_hostname: "{{ vsphere_esxi_host }}"
    guest_id: "{{ inventory_vm_guestid }}"
    template: "{{ inventory_template_name }}"
    disk:
      - size_gb: "{{ common_win_disk_size }}"
        type: "{{ vsphere_vm_type }}"
        datastore: "{{ vsphere_vm_disk_datastore }}"
    hardware:
      memory_mb: "{{ inventory_guest_vram }}"
      num_cpus: "{{ inventory_guest_vcpu }}"
      scsi: "{{ common_vm_hw_scsi }}"
    networks:
      - name: "{{ common_vm_net_name }}"
        ip: "{{ inventory_hostname }}"
        netmask: "{{ common_netmask }}"
        gateway: "{{ common_gateway }}"
    customization:
      autologoncount: 1
      autologon: true
      hostname: "{{ inventory_guest_hostname }}"
      dns_servers:
        - "{{ common_dns2 }}"
      timezone: "{{ common_timezone }}"
      password: "{{ template_password }}"
      # This powershell script is required for cross vlan WinRM to run the next tasks - Once playbook complete remove the firewall rule if needed
      runonce:
      - cmd /c echo New-NetFirewallRule -DisplayName "WinRM 5985" -Direction Inbound -LocalPort 5985 -Protocol TCP -RemoteAddress Any -Action Allow > C:\enable_winrm.ps1
      - powershell.exe -ExecutionPolicy Unrestricted -File C:\enable_winrm.ps1 -ForceNewSSLCert -EnableCredSSP
    wait_for_customization: yes
    wait_for_ip_address: True
  delegate_to: localhost

- name: Add host to Ansible inventory
  add_host:
    name: '{{ inventory_hostname }}'
    ansible_user: '{{ common_local_admin }}'
    ansible_password: '{{ template_password }}'
    ansible_connection: winrm
    ansible_winrm_transport: ntlm
    ansible_winrm_server_cert_validation: ignore
    ansible_winrm_port: 5985

- name: Wait for system to become reachable over WinRM
  wait_for_connection:
    timeout: 900
  delegate_to: '{{ inventory_hostname }}'

- name: Set upstream DNS server 
  win_dns_client:
    adapter_names: '*'
    ipv4_addresses:
    - '{{ ad_upstream_dns_1 }}'
    - '{{ ad_upstream_dns_2 }}'
  delegate_to: '{{ inventory_hostname }}'

- name: Stop the time service
  win_service:
    name: w32time
    state: stopped
  delegate_to: '{{ inventory_hostname }}'

- name: Set NTP Servers
  win_shell: 'w32tm /config /syncfromflags:manual /manualpeerlist:"{{ad_ntp_servers}}"'
  delegate_to: '{{ inventory_hostname }}'  

- name: Start the time service
  win_service:
    name: w32time
    state: started  
  delegate_to: '{{ inventory_hostname }}'

- name: Disable firewall for Domain, Public and Private profiles
  win_firewall:
    state: disabled
    profiles:
    - Domain
    - Private
    - Public
  tags: disable_firewall
  delegate_to: '{{ inventory_hostname }}'

- name: Reboot server
  win_reboot:
   msg: "Rebooting..."
   pre_reboot_delay: 5
  delegate_to: "{{ inventory_hostname }}"

- name: Install Active Directory
  win_feature: >
       name=AD-Domain-Services
       include_management_tools=yes
       include_sub_features=yes
       state=present
  register: result
  delegate_to: '{{ inventory_hostname }}'

- name: Create Domain
  win_domain: >
     dns_domain_name='{{ ad_domain }}'
     safe_mode_password='{{ ad_recovery_password }}'
  register: ad
  delegate_to: "{{ inventory_hostname }}"

- name: Reboot server
  win_reboot:
   msg: "Installing AD. Rebooting..."
   pre_reboot_delay: 5
  when: ad.changed
  delegate_to: "{{ inventory_hostname }}"

- name: Set internal DNS server 
  win_dns_client:
    adapter_names: '*'
    ipv4_addresses:
    - '127.0.0.1'
  delegate_to: '{{ inventory_hostname }}'

- name: Create reverse DNS zone
  win_shell: "Add-DnsServerPrimaryZone -NetworkID {{ad_reverse_dns_zone}} -ReplicationScope Forest"
  delegate_to: "{{ inventory_hostname }}"    
  retries: 30
  delay: 60
  register: result           
  until: result is succeeded

- name: Copy General PowerShell Scripts
  win_copy:
    src: scripts/powershell/general_scripts
    dest: C:/

- name: Copy AD PowerShell Scripts
  win_copy:
    src: scripts/powershell/ad_scripts
    dest: C:/

- name: Enable Remote Desktop
  win_command: powershell.exe -ExecutionPolicy ByPass -File C:/general_scripts/enable_rdp.ps1

- name: Import AD Users
  win_command: powershell.exe -ExecutionPolicy ByPass -File C:/ad_scripts/ad_import_users.ps1

- name: Add Users to Groups
  win_command: powershell.exe -ExecutionPolicy ByPass -File C:/ad_scripts/ad_assign_groups.ps1

- name: Enable firewall for Domain, Public and Private profiles
  win_firewall:
    state: enabled
    profiles:
    - Domain
    - Private
    - Public
  tags: enable_firewall
  delegate_to: '{{ inventory_hostname }}'

- name: Set New Domain Administrator Password
  win_user:
    name: administrator
    password: "{{ad_new_domain_admin_password}}"
    state: present
  delegate_to: '{{ inventory_hostname }}'
  ignore_errors: True  
