---
- name: Setup passwords
  hosts: localhost
  vars_files:
    - vars/vsphere_vars.yml
    - vars/common_vars.yml
  vars_prompt:
    - name: "vcenter_password"
      prompt: "Enter password for {{ vsphere_vcenter_username }} - {{ vsphere_vcenter_hostname }}"
      private: yes
    - name: "template_password"
      prompt: "Enter password for local administrator template for user {{ common_local_admin }}"
      private: yes
  tasks:
    - set_fact:
        vcenter_password: "{{ vcenter_password }}"
        template_password: "{{ template_password }}"

- name: Build Windows AD Forest
  hosts: dc
  become: false
  gather_facts: false
  collections:
    - community.vmware
  pre_tasks:
      - include_vars: vars/vsphere_vars.yml
      - include_vars: vars/common_vars.yml
      - include_vars: vars/ad_vars.yml
  vars:
    - vcenter_password: "{{ hostvars['localhost']['vcenter_password'] }}"
    - template_password: "{{ hostvars['localhost']['template_password'] }}"
  tasks:
    - import_tasks: tasks/vmware_create_ad/main.yml
  serial: 1

- name: Build Windows Server/s
  hosts: win_server
  become: false
  gather_facts: false
  collections:
    - community.vmware
  pre_tasks:
      - include_vars: vars/vsphere_vars.yml
      - include_vars: vars/common_vars.yml
      - include_vars: vars/ad_vars.yml
  vars:
    - vcenter_password: "{{ hostvars['localhost']['vcenter_password'] }}"
    - template_password: "{{ hostvars['localhost']['template_password'] }}"
  tasks:
    - import_tasks: tasks/vmware_create_windows_servers/main.yml
  serial: 1

- name: Build Windows Client/s
  hosts: win_client
  become: false
  gather_facts: false
  collections:
    - community.vmware
  pre_tasks:
      - include_vars: vars/vsphere_vars.yml
      - include_vars: vars/common_vars.yml
      - include_vars: vars/ad_vars.yml
  vars:
    - vcenter_password: "{{ hostvars['localhost']['vcenter_password'] }}"
    - template_password: "{{ hostvars['localhost']['template_password'] }}"
  tasks:
    - import_tasks: tasks/vmware_create_windows_clients/main.yml
  serial: 1

- name: Build Linux Server/s
  hosts: lin_server
  become: false
  gather_facts: false
  collections:
    - community.vmware
  pre_tasks:
      - include_vars: vars/vsphere_vars.yml
      - include_vars: vars/common_vars.yml
      - include_vars: vars/ad_vars.yml
  vars:
    - vcenter_password: "{{ hostvars['localhost']['vcenter_password'] }}"
  tasks:
    - import_tasks: tasks/vmware_create_linux_servers/main.yml
  serial: 1

- name: Build Linux Client/s
  hosts: lin_client
  become: false
  gather_facts: false
  collections:
    - community.vmware
  pre_tasks:
      - include_vars: vars/vsphere_vars.yml
      - include_vars: vars/common_vars.yml
      - include_vars: vars/ad_vars.yml
  vars:
    - vcenter_password: "{{ hostvars['localhost']['vcenter_password'] }}"
  tasks:
    - import_tasks: tasks/vmware_create_linux_clients/main.yml
  serial: 1