---
- name: Setup passwords
  hosts: localhost
  vars_files:
    - vars/main.yml
  vars_prompt:
    - name: "vcenter_password"
      prompt: "Enter password for {{ vcenter_username }} - {{ vcenter_hostname }}"
      private: yes
    - name: "local_adminpassword"
      prompt: "Enter password for Windows local administrator template"
      private: yes
  tasks:
    - set_fact:
        vcenter_password: "{{ vcenter_password }}"
        temp_password: "{{ local_adminpassword }}"
        local_adminpassword: "{{ local_adminpassword }}"

- name: Build Windows AD Forest
  hosts: dc
  become: false
  gather_facts: false
  collections:
    - community.vmware
  pre_tasks:
      - include_vars: vars/main.yml
  vars:
    - vcenter_password: "{{ hostvars['localhost']['vcenter_password'] }}"
    - temp_password: "{{ hostvars['localhost']['local_adminpassword'] }}"
  tasks:
    - import_tasks: tasks/vmware_create_ad/main.yml
  serial: 1

- name: Build Windows Environment
  hosts: win
  become: false
  gather_facts: false
  collections:
    - community.vmware
  pre_tasks:
      - include_vars: vars/main.yml
  vars:
    - vcenter_password: "{{ hostvars['localhost']['vcenter_password'] }}"
    - local_adminpassword: "{{ hostvars['localhost']['local_adminpassword'] }}"
  tasks:
    - import_tasks: tasks/vmware_create_windows/main.yml
  serial: 1

- name: Build Linux Environment
  hosts: lin
  become: false
  gather_facts: false
  collections:
    - community.vmware
  pre_tasks:
      - include_vars: vars/main.yml
  vars:
    - vcenter_password: "{{ hostvars['localhost']['vcenter_password'] }}"
  tasks:
    - import_tasks: tasks/vmware_create_linux/main.yml
  serial: 1