---
- name: Create Linux Client Virtual Machine/s
  vmware_guest:
    hostname: "{{ vsphere_vcenter_hostname }}"
    username: "{{ vsphere_vcenter_username }}"
    password: "{{ vcenter_password }}"
    validate_certs: "{{ vsphere_vcenter_validate_certs }}"
    datacenter: "{{ vsphere_vcenter_datacenter }}"
    name: "{{ inventory_guest_hostname }}"
    folder: "{{ vsphere_vm_folder }}"
    state: "{{ common_vm_state }}"
    guest_id: "{{ inventory_vm_guestid }}"
    esxi_hostname: "{{ vsphere_esxi_host }}"
    template: "{{ inventory_template_name }}"
    disk:
      - size_gb: "{{ common_lin_disk_size }}"
        type: "{{ vsphere_vm_type }}"
        datastore: "{{ vsphere_vm_disk_datastore }}"
    hardware:
      memory_mb: "{{ inventory_guest_vram }}"
      num_cpus: "{{ inventory_guest_vcpu }}"
      scsi: "{{ common_vm_hw_scsi }}"
    networks:
      - name: "{{ common_vm_net_name }}"
        ip: "{{ inventory_hostname }}"
        netmask: "{{ common_netmask }}"
        gateway: "{{ common_gateway }}"
    customization:
      domain: "{{ ad_domain }}"
      dns_servers:
        - "{{ groups['dc'][0] }}"
        - "{{ common_dns2 }}"
      dns_suffix:
        - "{{ ad_domain }}"
    wait_for_ip_address: True
  delegate_to: localhost

  # Connect via ssh / inventory host in memory
  
- name: Add host to Ansible inventory
  ansible.builtin.add_host:
    hostname: '{{ inventory_hostname }}'
    ansible_user: '{{ common_lin_local_admin }}'
    ansible_password: '{{ template_password }}'
    # always trust, don't store keys
    ansible_ssh_extra_args: '-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'

- name: Wait for system to become reachable over SSH
  wait_for_connection:
    timeout: 900
  delegate_to: '{{ inventory_hostname }}'

  # Add GUI (CentOS)
  
- name: CentOS - Install GUI
  shell: |
    yum groupinstall "GNOME Desktop" -y
    systemctl set-default graphical.target
  when: inventory_template_name.find("centos") != -1
  become: yes
  delegate_to: '{{ inventory_hostname }}'

  # Add GUI (Ubuntu)

- name: Ubuntu - Update and upgrade apt packages
  ansible.builtin.apt:
    upgrade: yes
    update_cache: yes
    cache_valid_time: 86400
  when: inventory_template_name.find("ubuntu") != -1
  become: yes
  delegate_to: '{{ inventory_hostname }}'

- name: Ubuntu - Install GUI (Ubuntu) - gnome-shell
  ansible.builtin.apt:
    name: gnome-shell
    state: present
  when: inventory_template_name.find("ubuntu") != -1
  become: yes
  delegate_to: '{{ inventory_hostname }}'

- name: Ubuntu - Install GUI (Ubuntu) - ubuntu-desktop
  ansible.builtin.apt:
    name: ubuntu-desktop
    state: present
  when: inventory_template_name.find("ubuntu") != -1
  become: yes
  delegate_to: '{{ inventory_hostname }}'

- name: Reboot machine
  ansible.builtin.reboot:
    msg: "Rebooting..."
  become: yes
  delegate_to: '{{ inventory_hostname }}'

  # Join Domain (CentOS 7)

- name: CentOS - Install the epel-release - For python-pip
  yum:
    name: epel-release
    state: present
  become: yes
  when: inventory_template_name.find("centos") != -1
  delegate_to: '{{ inventory_hostname }}'

- name: CentOS - Install the required packages
  yum:
    name: realmd,sssd,oddjob,oddjob-mkhomedir,adcli,samba-common,samba-common-tools,ntpdate,ntp,python-pip
    state: present
  become: yes
  when: inventory_template_name.find("centos") != -1
  delegate_to: '{{ inventory_hostname }}'

- name: CentOS - Restart realmd
  service:
    name: realmd
    state: restarted
  become: yes
  when: inventory_template_name.find("centos") != -1
  delegate_to: '{{ inventory_hostname }}'

- name: CentOS - Install pexpect using pip
  pip:
    name: pexpect
  become: yes
  when: inventory_template_name.find("centos") != -1
  delegate_to: '{{ inventory_hostname }}'

- name: CentOS - Join system to AD
  expect:
    command: /bin/bash -c "/usr/sbin/realm join --user={{ common_domain_admin_simple_name }}@{{ ad_domain }} --computer-ou={{ ad_centos_ou_membership }} {{ ad_domain }}
    responses:
      Password for *: "{{ ad_new_domain_admin_password }}"
  become: yes
  when: inventory_template_name.find("centos") != -1
  delegate_to: '{{ inventory_hostname }}'

- name: CentOS - Add default_domain_suffix to sssd.conf
  lineinfile:
    dest: /etc/sssd/sssd.conf
    line: 'default_domain_suffix = {{ ad_domain }}'
    insertafter: '^\[sssd\]'
  become: yes
  when: inventory_template_name.find("centos") != -1
  delegate_to: '{{ inventory_hostname }}'

- name: CentOS - Restart sssd
  service:
    name: sssd
    state: restarted
  become: yes
  when: inventory_template_name.find("centos") != -1
  delegate_to: '{{ inventory_hostname }}'

- name: CentOS - Allow all users to logon to the system
  command: /bin/bash -c "/usr/sbin/realm permit --all"
  when: inventory_template_name.find("centos") != -1
  become: yes
  delegate_to: '{{ inventory_hostname }}'

- name: CentOS - Add the Domain Admins AD Group to sudoers file
  lineinfile:
    dest: /etc/sudoers
    line: '%domain\ admins@{{ ad_domain }}        ALL=(ALL)       ALL'
    insertafter: '^%wheel'
  become: yes
  when: inventory_template_name.find("centos") != -1
  delegate_to: '{{ inventory_hostname }}'